services:
  - type: web
    name: hotel-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase: hotel-db

databases:
  - name: hotel-db
    region: oregon
    plan: free
    databaseName: hotel
